const workbookFields = [
    "App Development",
    "Artificial Intelligence",
    "Augmented Reality",
    "Cybersecurity",
    "Data Science",
    "Desktop App Development",
    "Extended Reality",
    "Game Development",
    "Machine Learning",
    "Mixed Reality",
    "Mobile App Development",
    "Vanilla (C)",
    "Vanilla (C++)",
    "Vanilla (C#)",
    "Vanilla (Go)",
    "Vanilla (Java)",
    "Vanilla (JavaScript)",
    "Vanilla (Julia)",
    "Vanilla (Kotlin)",
    "Vanilla (Python)",
    "Vanilla (Ruby)",
    "Vanilla (Rust)",
    "Vanilla (Swift)",
    "Vanilla (TypeScript)",
    "Virtual Reality",
    "Web Development",
    "Web3",
    "Others",
];

export default workbookFields;
